# delete after done.
volumes:
  redis-data:
  lanraragi-data:
  prometheus-data:

services:

  redis:
    image: redis:7.2
    container_name: redis
    restart: unless-stopped
    ports:
      - 127.0.0.1:6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      start_period: 10s
    volumes:
      - redis-data:/data

  lanraragi:
    build:
      context: .
      dockerfile: ./tools/build/docker/Dockerfile
    container_name: lanraragi
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - "LRR_REDIS_ADDRESS=redis:6379"
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - lanraragi-data:/home/koyomi

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./tools/observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    depends_on:
      - lanraragi

  grafana:
    image: grafana/grafana-oss:main-ubuntu
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3001:3000
    depends_on:
      - prometheus
    volumes:
      - ./tools/observability/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml:ro
    environment:
      - GF_SECURITY_ADMIN_USER=grafana
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_LOG_LEVEL=warning
