//! Build-time generated route lists and boot-time secured-set construction.
//!
//! `AUTH_REQUIRED_ROUTES` and `ANONYMOUS_ROUTES` are emitted by `build.rs`
//! from `tools/openapi.yaml`. Paths lack the `/api` prefix; middleware prepends
//! it at boot so `MatchedPath` lookups match directly.

use std::collections::HashSet;

use axum::http::Method;

use crate::db::config::LrrConfig;

// Generated by build.rs from tools/openapi.yaml.
include!(concat!(env!("OUT_DIR"), "/auth_routes.rs"));

/// Constructs the secured set from `AUTH_REQUIRED_ROUTES` plus the two
/// runtime overlays:
/// - `authprogress=true` adds `PUT /api/archives/{id}/progress/{page}`.
/// - `nofunmode=true` adds every `ANONYMOUS_ROUTES` entry.
///
/// Paths from the generated slices lack `/api`; this function prepends it so
/// `MatchedPath` comparisons in the middleware work without per-request string
/// ops.
pub fn build_secured_set(config: &LrrConfig) -> HashSet<(Method, String)> {
    let mut set = HashSet::new();

    for (method, path) in AUTH_REQUIRED_ROUTES {
        let m = method.parse::<Method>().expect("invalid method in AUTH_REQUIRED_ROUTES");
        set.insert((m, format!("/api{path}")));
    }

    if config.authprogress {
        set.insert((Method::PUT, "/api/archives/{id}/progress/{page}".to_string()));
        set.insert((Method::PUT, "/api/tankoubons/{id}/progress/{page}".to_string()));
    }

    if config.nofunmode {
        for (method, path) in ANONYMOUS_ROUTES {
            let m = method.parse::<Method>().expect("invalid method in ANONYMOUS_ROUTES");
            set.insert((m, format!("/api{path}")));
        }
    }

    set
}
