#!/usr/bin/env perl

use strict;
use warnings;

BEGIN { printf "[TIMING] perl_started: delta=%ds\n", time() - $^T; }

use FindBin;
BEGIN { unshift @INC, "$FindBin::Bin/../lib"; }
use Mojolicious::Commands;

# Start command line interface for application
Mojolicious::Commands->start_app('LANraragi');
